#ifndef __ENTITY_TYPE_H__
#define __ENTITY_TYPE_H__

#ifdef __cplusplus
extern "C"
{
#endif

#define NODE_PROFILE_ZIGBEE 1

#define ENTITY_TYPE_ACCOUNT 1
#define ENTITY_TYPE_CLUSTER 2
#define ENTITY_TYPE_TERMINAL 3
#define ENTITY_TYPE_TUID 4
#define ENTITY_TYPE_FAMILY 5
#define ENTITY_TYPE_GATEWAY 6
#define ENTITY_TYPE_NODE 7
#define ENTITY_TYPE_DEVICE 8
#define ENTITY_TYPE_VALUE 9
#define ENTITY_TYPE_ROOM 10
#define ENTITY_TYPE_SCENE 11
#define ENTITY_TYPE_MASTER 12
#define ENTITY_TYPE_SLAVE 13
#define ENTITY_TYPE_GANGER 14
#define ENTITY_TYPE_SCHEDULE 15

#define PROPERTY_ACCOUNT_TERMINAL 100
#define PROPERTY_ACCOUNT_RESET 101
#define PROPERTY_ACCOUNT_CLUSTER 102

#define PROPERTY_TERMINAL_ID 100
#define PROPERTY_TERMINAL_TYPE 101
#define PROPERTY_TERMINAL_RESET 102

#define PROPERTY_FAMILY_NAME 100
#define PROPERTY_FAMILY_CLUSTER 101

#define PROPERTY_CLUSTER_ID 100
#define PROPERTY_CLUSTER_PIN 101

#define PROPERTY_TUID_IDX 100

#define PROPERTY_NODE_MAC 100
#define PROPERTY_NODE_SHORT 101
#define PROPERTY_NODE_CAPABILITY 102
#define PROPERTY_NODE_PROFILE 103
#define PROPERTY_NODE_ONLINE 104

#define PROPERTY_DEVICE_NODE 100
#define PROPERTY_DEVICE_CATEGORY 101
#define PROPERTY_DEVICE_LINK 102
#define PROPERTY_DEVICE_NAME 103
#define PROPERTY_DEVICE_SLAVE 104
#define PROPERTY_DEVICE_SIMPLE_DESC 105

#define PROPERTY_DEVICE_ZIGBEE_PROFILE 110
#define PROPERTY_DEVICE_ZIGBEE_DEVICE 111
#define PROPERTY_DEVICE_ZIGBEE_ENDPOINT 112
#define PROPERTY_DEVICE_ZIGBEE_CLUSTERS_IN 113
#define PROPERTY_DEVICE_ZIGBEE_CLUSTERS_OUT 114

#define PROPERTY_VALUE_DEVICE 100
#define PROPERTY_VALUE_BOOL 101
#define PROPERTY_VALUE_INT8 102
#define PROPERTY_VALUE_INT16 103
#define PROPERTY_VALUE_INT32 104
#define PROPERTY_VALUE_INT48 105
#define PROPERTY_VALUE_INT64 106
#define PROPERTY_VALUE_BUFFER 107
#define PROPERTY_VALUE_STRING 108

#define PROPERTY_GATEWAY_RESET 100
#define PROPERTY_GATEWAY_DHCP 101
#define PROPERTY_GATEWAY_IP 102
#define PROPERTY_GATEWAY_MASK 103
#define PROPERTY_GATEWAY_PRIDNS 104
#define PROPERTY_GATEWAY_SECDNS 105
#define PROPERTY_GATEWAY_MAC 106

#define PROPERTY_SLAVE_MASTER 100
#define PROPERTY_SLAVE_DEVICE 101
#define PROPERTY_SLAVE_COMMAND 102
#define PROPERTY_SLAVE_TRANSITION 103
#define PROPERTY_SLAVE_MANUAL 104

#define PROPERTY_MASTER_SCENE_ON 100
#define PROPERTY_MASTER_SCENE_OFF 101
#define PROPERTY_MASTER_LINK 102

#define PROPERTY_ROOM_FAMILY 100
#define PROPERTY_ROOM_LINK 101
#define PROPERTY_ROOM_NAME 102
#define PROPERTY_ROOM_VISIBLE 103

#define PROPERTY_SCENE_FAMILY 100
#define PROPERTY_SCENE_LINK 101
#define PROPERTY_SCENE_NAME 102

#define PROPERTY_GANGER_LINK 100
#define PROPERTY_GANGER_TERMINAL 101

#define PROPERTY_SCHEDULE_LINK 100
#define PROPERTY_SCHEDULE_OWNER 101
#define PROPERTY_SCHEDULE_COMMAND 102
#define PROPERTY_SCHEDULE_YEAR 103
#define PROPERTY_SCHEDULE_MONTH 104
#define PROPERTY_SCHEDULE_DAY 105
#define PROPERTY_SCHEDULE_WEEK 106
#define PROPERTY_SCHEDULE_HOUR 107
#define PROPERTY_SCHEDULE_MINUTE 108
#define PROPERTY_SCHEDULE_SECOND 109

#define TERMINAL_TYPE_GATEWAY 1
#define TERMINAL_TYPE_MOBILE 2
#define TERMINAL_TYPE_ALL 0xff

#define DEVICE_CATEGORY_GATEWAY (0x0100ul)
#define DEVICE_CATEGORY_LIGHT (0x0200ul)
#define DEVICE_CATEGORY_SOCKET (0x0300ul)
#define DEVICE_CATEGORY_SWITCH (0x0400ul)

#define ENTITY_COMMAND_CREATE 1
#define ENTITY_COMMAND_DELETE 2

#define ENTITY_COMMAND_DEVICE_OPERATE_ONOFF 100
#define ENTITY_COMMAND_DEVICE_OPERATE_LEVEL 101

#define ENTITY_COMMAND_MASTER_OPERATE 100
#define ENTITY_COMMAND_MASTER_ROOM_APPLY 101
#define ENTITY_COMMAND_MASTER_SCENE_APPLY 102

#define ENTITY_COMMAND_SLAVE_APPLY 100

#define ENTITY_COMMAND_GATEWAY_DISCOVER_START 100
#define ENTITY_COMMAND_GATEWAY_DISCOVER_STOP 101

#define MAX_LINK (6ul)

#ifdef __cplusplus
}
#endif

#endif
