#ifndef __OPCODE_H__
#define __OPCODE_H__

#define OPCODE_RMP_RETRY 1
#define OPCODE_RMP_ACK 2

#define OPCODE_AUTH_REQ 11
#define OPCODE_AUTH_RSP 12
#define OPCODE_AUTH_VERIFY 13
#define OPCODE_AUTH_CONFIRM 14

#define OPCODE_MANAGER_KICKOUT 21
#define OPCODE_TIME_REQ 22
#define OPCODE_TIME_RESP 23

#define OPCODE_CLUSTER_JOIN 31
#define OPCODE_CLUSTER_LEAVE 32

#define OPCODE_INTERNAL_DECLARE 41
#define OPCODE_INTERNAL_INVITE 42
#define OPCODE_INTERNAL_ACCEPT 43

#define OPCODE_TERMINAL_SYNC 51
#define OPCODE_TERMINAL_UPDATE 52
#define OPCODE_TERMINAL_DELETE 53

#define OPCODE_ENTITY_SYNC 61
#define OPCODE_ENTITY_UPDATE 62
#define OPCODE_ENTITY_CREATE 63
#define OPCODE_ENTITY_DELETE 64
#define OPCODE_ENTITY_COMMAND 65
#define OPCODE_ENTITY_RESPONSE 66
#define OPCODE_ENTITY_LINK 67
#define OPCODE_ENTITY_EVENT 68

#define OPCODE_PROPERTY_UPDATE 71
#define OPCODE_PROPERTY_CREATE 72
#define OPCODE_PROPERTY_DELETE 73
#define OPCODE_PROPERTY_SET 74

#define OPCODE_GANGER_SYNC 81

#define EVENT_ENTITY_DEVICE_KEY 1

#endif
