#ifndef __SIGMA_OPCODE_H__
#define __SIGMA_OPCODE_H__

#define OPCODE_LINK_SEND 0
#define OPCODE_LINK_ACK 1
#define OPCODE_LINK_RETRANSMIT 2

#define OPCODE_CRYPTO_AUTH 1
#define OPCODE_CRYPTO_REQ 2
#define OPCODE_CRYPTO_RESP 3
#define OPCODE_CRYPTO_FAILED 4

#define OPCODE_REGISTER_REQ 1
#define OPCODE_REGISTER_RESP 2
#define OPCODE_REGISTER_FAILED 3

#define OPCODE_CLUSTER_JOIN 1
#define OPCODE_CLUSTER_LEAVE 2
#define OPCODE_CLUSTER_INVITE 3
#define OPCODE_CLUSTER_REJECT 4
#define OPCODE_CLUSTER_ACCEPT 5
#define OPCODE_CLUSTER_DISCOVER 6
#define OPCODE_CLUSTER_DECLARE 7
#define OPCODE_CLUSTER_PUBLISH 8

#define OPCODE_RPC_RESPONSE 0
#define OPCODE_RPC_CAPABILITY 1

#define OPCODE_RPC_ENTITY_CREATE (0x0101)
#define OPCODE_RPC_ENTITY_RELEASE (0x0102)
#define OPCODE_RPC_ENTITY_WRITE (0x0103)
#define OPCODE_RPC_ENTITY_READ (0x0104)
#define OPCODE_RPC_ENTITY_ACTION (0x0105)
#define OPCODE_RPC_ENTITY_ITERATOR_CREATE (0x0106)
#define OPCODE_RPC_ENTITY_ITERATOR_RELEASE (0x0107)
#define OPCODE_RPC_ENTITY_ITERATOR_FILTER (0x0108)
#define OPCODE_RPC_ENTITY_ITERATOR_EXECUTE (0x0109)

#endif
