#!/bin/sh /etc/rc.common

START=85
USE_PROCD=1
start_service() {
    procd_open_instance
    procd_set_param respawn
    procd_set_param command /bin/iotsigma_gateway
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/iotsigma.pid
    procd_close_instance

    echo "start done."
}

stop_service() {
    echo "stop done."
}

restart() {
    stop
    start
}
